packages:
  - apps/*
  - packages/*
allowBuilds:
  '@scarf/scarf': false
  '@parcel/watcher': set this to true or false
  nx: true
  unrs-resolver: false
  esbuild: false
  "@swc/core": false
  "@nestjs/core": false
